# Generated by Django 3.2.5 on 2021-07-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('chef_name', models.CharField(max_length=255)),
                ('image_url', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('method', models.TextField()),
                ('ingredient', models.TextField()),
                ('image_url', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('chefuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.chefuser')),
            ],
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image_url', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSurvey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('question_one', models.TextField()),
                ('question_two', models.TextField()),
                ('question_three', models.TextField()),
                ('question_four', models.TextField()),
                ('question_five', models.TextField()),
                ('question_six', models.TextField()),
                ('question_seven', models.TextField()),
                ('question_eight', models.TextField()),
                ('question_nine', models.TextField()),
                ('question_ten', models.TextField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCommentary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('show_comment', models.BooleanField(default=True)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.continent')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.country')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ChefPhoneNumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('chefuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.chefuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChefImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='')),
                ('chefuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.chefuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChefAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('chefuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.chefuser')),
                ('continent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.continent')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('chefuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.chefuser')),
                ('regularuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_management_app.regularuser')),
            ],
        ),
    ]
