# Generated by Django 3.2.5 on 2021-07-23 06:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='decription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
