# Generated by Django 3.2.5 on 2021-07-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularuser',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
