# Generated by Django 3.2.5 on 2021-07-22 04:51

import chef_management_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefimages',
            name='url',
            field=models.ImageField(null=True, upload_to=chef_management_app.models.filepath_chef_image),
        ),
        migrations.AlterField(
            model_name='chefphonenumer',
            name='number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeimages',
            name='url',
            field=models.ImageField(null=True, upload_to=chef_management_app.models.filepath_recipe_image),
        ),
    ]
