# Generated by Django 3.2.5 on 2021-07-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management_app', '0002_auto_20210722_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefaddress',
            name='continent_id',
        ),
        migrations.RemoveField(
            model_name='recipeaddress',
            name='continent_id',
        ),
    ]
